# Permalinks
permalink:           pretty

# Setup
safe:                false
title:               Things on a Heap
tagline:             A Collection of Programming Ramblings by chjdev
url:                 https://chjdev.com
enforce_ssl:         chjdev.com
paginate:            6
baseurl:             ""
gems:                [jekyll-paginate, jekyll-gist]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:             :compressed

# About/contact
author:
  name:              Christian Junker
  url:               https://twitter.com/chjdev
  email:             chjdev@gmail.com

pages_list:       
    About: '/about'
    Archive: '/archive'
    Feed: '/atom.xml'
