# Permalinks
permalink:           pretty

# Setup
title:               Things on a Heap
tagline:             A Collection of Programming Ramblings by chjdev
description:         A Collection of Programming Ramblings by chjdev
url:                 https://chjdev.com
enforce_ssl:         chjdev.com
paginate:            6
baseurl:             ""
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - assets/2016/01/node_modules

#github-pages
#markdown: redcarpet

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:             :compressed

# About/contact
author:
  name:              Christian Junker
  url:               https://twitter.com/chjdev

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
